Added some dependency checks.

diff --git a/bin/grace2pdf b/bin/grace2pdf
--- a/bin/grace2pdf
+++ b/bin/grace2pdf
@@ -8,6 +8,16 @@
 # olsonbg: bin/pdf2png @ https://github.com/olsonbg/dotfiles
 #
 
+if ! hash xmgrace 2/dev/null ; then
+	echo "Required program not found (xmgrace), exiting."
+	exit
+fi
+
+if ! hash pdfcrop 2/dev/null ; then
+	echo "Required program not found (pdfcrop), exiting."
+	exit
+fi
+
 P_GRACE=$(which xmgrace)
 P_PDFCROP=$(which pdfcrop)
 
diff --git a/bin/pdf2png b/bin/pdf2png
--- a/bin/pdf2png
+++ b/bin/pdf2png
@@ -11,6 +11,11 @@
 # olsonbg: bin/pdf2png @ https://github.com/olsonbg/dotfiles
 #
 
+if ! hash convert 2/dev/null ; then
+	echo "Required program not found (convert: from ImageMagick package), exiting."
+	exit
+fi
+
 P_CONVERT="$(which convert)"
 P_FILE="$(which file)"
 
